version: "3.4"

services:
  develop:
    image: registry.develop.vsmart00.com/glara
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile
      network: host
  standby:
    image: registry.standby.vsmart00.com/glara
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile
      network: host
  eksrussia:
    image: registry.russia.vsmart00.com/glara
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile
      network: host
  eksegypt:
    image: registry.egypt.vsmart00.com/glara
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile
      network: host
  global:
    image: registry.global.dentalclever.com/glara
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile
      network: host
  clever:
    image: registry.clever.vsmart00.com/glara
    build:
      context: ./
      dockerfile: dockerfiles/dockerfile
      network: host