apiVersion: v1
kind: Service
metadata:
  name: kubelog-go-service
  namespace: logger
  labels:
    app: kubelog-go
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: kubelog-go