FROM  golang:1.17.7-stretch AS builder

WORKDIR /usr/local/app

COPY . .

RUN go mod download 

RUN cp -av envs/out.cluster.env ./.env

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o kubelog-go .

FROM scratch

COPY --from=builder /usr/local/app/ /

CMD ["/glara"]