FROM  golang:1.17.7-stretch AS builder

WORKDIR /usr/local/app

COPY . .

RUN go mod vendor 

# RUN go mod download

ENV VERSION=1.1.0

# RUN cp -av envs/out.cluster.env ./.env

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o glara .

FROM scratch

COPY --from=builder /usr/local/app/ /

ENTRYPOINT [ "/glara","inspect" ] 