name: develop
on: [push]
jobs:  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: "recursive"
        #   token: ${{ secrets.TOKEN }}
      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: glara
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./dockerfiles/dockerfile

      - name: Push
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set-Kubernetes-Credentials
        id: set-kubeconfig
        uses: actions/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.DEVELOP_KUBE_CONFIG}}

      - name : Restart-Glara-deployment
        id: restart-glara
        uses: actions-hub/kubectl@master
        with: 
          args: rollout restart deployment glara --namespace=glara
