name: develop-deploy
on: [push]
jobs:  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: glara
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./dockerfiles/dockerfile

      - name: Push
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Restart-deployments
        uses: Jberlinsky/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.DEVELOP_KUBE_CONFIG }}
        with:
          args: rollout restart deployment glara -n=glara